### ISSUE TITLE
#1 역할 분담

### ISSUE THREAD

**Issue by JaeWookLim** [JaeWookLim/ReverseProposal_System#1]
Cats 순서도 정리 - 강한빛

Shop, Others 순서도 정리 - 유윤재

Goodies, Camera 순서도 정리 - 곽수인

Yard, Setting, News 순서도 정리 - 강송모

Tutorial, Gifts 순서도 정리 - 임재욱

**Comment by suin0730** [comment]
전체 순서도 정리를 지난번 역기획서 흐름대로 할지 목적을 기준으로 잡을지 회의.
UI기준으로 전체 메뉴를 분량에 맞추어 5개로 나눈 후 사다리타기로 배정.
